# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_deck_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='definition',
            field=models.CharField(default='definition', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='term',
            field=models.CharField(default='term', max_length=100),
            preserve_default=False,
        ),
    ]
